---
kind: pipeline
name: Test Build

platform:
  os: linux
  arch: arm64

steps:
- name: Build
  image: plugins/docker
  settings:
    repo: poksiala/caddy-builder
    dry_run: true
  
trigger:
  branch:
    exclude:
      - master

---
kind: pipeline
name: Publish Hub

platform:
  os: linux
  arch: arm64

- name: Publish
  image: plugins/docker
  settings:
    username: poksiala
    password:
      from_secret: docker_password
    repo: poksiala/caddy
    tags: builder

trigger:
  branch:
  - master
  event:
  - push

---
kind: pipeline
name: Publish Registry

platform:
  os: linux
  arch: arm64

- name: Publish
  image: plugins/docker
  settings:
    username: poksiala
    password:
      from_secret: docker_password
    repo: registry.pohina.io/caddy
    registry: registry.pohina.io
    tags: builder

trigger:
  branch:
  - master
  event:
  - push
